### ISSUE TITLE
pdns-admin-uwsgi docker-compose error

### ISSUE THREAD

**Issue by legolass73** [pschiffe/docker-pdns#36]
Hello, i get this error start services with docker-compose:

Traceback (most recent call last):
  File "/opt/powerdns-admin/create_db.py", line 6, in <module>
    from app import db
  File "/opt/powerdns-admin/app/__init__.py", line 52, in <module>
    from app import views, models
  File "/opt/powerdns-admin/app/views.py", line 17, in <module>
    from .models import User, Domain, Record, Server, History, Anonymous, Setting, Language, DomainSetting, Page
  File "/opt/powerdns-admin/app/models.py", line 44, in <module>
    API_EXTENDED_URL = utils.pdns_api_extended_uri(PDNS_VERSION)
  File "/opt/powerdns-admin/app/lib/utils.py", line 146, in pdns_api_extended_uri
    if StrictVersion(version) >= StrictVersion('4.0.0'):
  File "/usr/lib64/python2.7/distutils/version.py", line 140, in __cmp__
    compare = cmp(self.version, other.version)
AttributeError: StrictVersion instance has no attribute 'version'

**Comment by pschiffe** [comment]
Hello. Most likely you are missing `PDNS_VERSION=4.2` env var for your uwsgi container, see #29 for more details.

**Comment by legolass73** [comment]
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "/opt/powerdns-admin/app/__init__.py", line 52, in <module>
    from app import views, models
  File "/opt/powerdns-admin/app/views.py", line 17, in <module>
    from .models import User, Domain, Record, Server, History, Anonymous, Setting, Language, DomainSetting, Page
  File "/opt/powerdns-admin/app/models.py", line 44, in <module>
    API_EXTENDED_URL = utils.pdns_api_extended_uri(PDNS_VERSION)
  File "/opt/powerdns-admin/app/lib/utils.py", line 146, in pdns_api_extended_uri
    if StrictVersion(version) >= StrictVersion('4.0.0'):
  File "/usr/lib64/python2.7/distutils/version.py", line 140, in __cmp__
    compare = cmp(self.version, other.version)
AttributeError: StrictVersion instance has no attribute 'version'
VACUUM: pidfile removed.

![Screenshot_3](https://user-images.githubusercontent.com/5279851/85227728-7ded3d00-b3df-11ea-84c9-0a723686d5c5.png)

**Comment by pschiffe** [comment]
Are you using this tag `pschiffe/pdns-admin-uwsgi:ngoduykhanh`? What version of power dns server are you trying to manage?

**Comment by legolass73** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/5279851/85338912-7020e000-b4e3-11ea-8135-db28126d89d4.png)
![Screenshot_4](https://user-images.githubusercontent.com/5279851/85338916-70b97680-b4e3-11ea-8bc5-0a8b0923b443.png)

**Comment by pschiffe** [comment]
yep, I think that's the problem. You are using `pschiffe/pdns-admin-uwsgi:latest`, but you need to use `pschiffe/pdns-admin-uwsgi:ngoduykhanh` and `pschiffe/pdns-admin-static:ngoduykhanh` - these are the new, maintained versions. I'm sorry the readme is more complicated than it should be..

**Comment by legolass73** [comment]
new error with new docker-compose:

**Comment by legolass73** [comment]
new error on new docker-compose:
error: 
```Traceback (most recent call last):
  File "/usr/local/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 257, in locate_app
    return find_best_app(script_info, module)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/opt/powerdns-admin/powerdnsadmin/__init__.py", line 54, in create_app
    app.config.from_object('powerdnsadmin.default_config')
  File "/usr/local/lib/python3.7/site-packages/flask/config.py", line 174, in from_object
    obj = import_string(obj)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/utils.py", line 568, in import_string
    __import__(import_name)
  File "/opt/powerdns-admin/powerdnsadmin/default_config.py", line 21, in <module>
    SQLALCHEMY_DATABASE_URI = 'mysql://' + SQLA_DB_USER + ':' + SQLA_DB_PASSWORD + '@' + SQLA_DB_HOST + ':' + SQLA_DB_PORT + '/' + SQLA_DB_NAME
TypeError: can only concatenate str (not "int") to str```

docker compose: 
```version: '3.6'

services:
  pdns-mysql:
    image: mariadb:latest
    hostname: pdns-mysql
    container_name: pdns-mysql
    restart: always
    domainname: sservais.cf
    volumes:
      - pdns-mysql:/var/lib/mysql
    cap_add:
      - SYS_NICE
    networks:
      pdns:
        ipv4_address: 172.16.0.1
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - MYSQL_DATABASE=powerdns
      - MYSQL_USER=powerdns
      - MYSQL_PASSWORD=sqladbpassword
    command: --default-authentication-plugin=mysql_native_password
    
  pdns-master:
    image: pschiffe/pdns-mysql
    hostname: pdns-master
    container_name: pdns-master
    restart: always
    domainname: sservais.cf
    networks:
      pdns:
        ipv4_address: 172.16.0.2
    ports:
      - '53:53'
      - '53:53/udp'
      - '8081:8081'
    environment:
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=SecretApi
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=secret
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_soa_minimum_ttl=1200
      - PDNS_default_soa_name=eridan.sservais.cf
      - PDNS_default_soa_mail=hostmaster.sservais.cf
      - PDNS_allow_axfr_ips=0.0.0.0
      - PDNS_gmysql_password=sqladbpassword
      - PDNS_gmysql_user=powerdns
      - PDNS_gmysql_host=172.16.0.1
      - PDNS_gmysql_dbname=powerdns
    links:
      - pdns-mysql:mysql
    depends_on:
      - pdns-mysql

  pdns-admin-uwsgi:
    image: pschiffe/pdns-admin-uwsgi:ngoduykhanh
    hostname: pdns-admin-uwsgi
    container_name: pdns-admin-uwsgi
    restart: always
    domainname: sservais.cf
    networks:
      pdns:
        ipv4_address: 172.16.0.3
    environment:
      - PDNS_ADMIN_SQLA_DB_HOST='172.16.0.1'
      - PDNS_ADMIN_SQLA_DB_PORT=3306
      - PDNS_ADMIN_SQLA_DB_USER='powerdns'
      - PDNS_ADMIN_SQLA_DB_PASSWORD='sqladbpassword'
      - PDNS_ADMIN_SQLA_DB_NAME='powerdns'
      - PDNS_API_URL="http://172.16.0.2:8081/"
      - PDNS_API_KEY="SecretApi"
    links:
      - pdns-master:pdns
      - pdns-mysql:mysql
    depends_on:
      - pdns-mysql
      - pdns-master

  pdns-admin-web:
    image: pschiffe/pdns-admin-static:ngoduykhanh
    hostname: pdns-admin-web
    container_name: pdns-admin-web
    restart: always
    domainname: sservais.cf
    networks:
      pdns:
        ipv4_address: 172.16.0.4
    ports:
      - '8080:80'
    links:
      - pdns-admin-uwsgi:pdns-admin-uwsgi
    depends_on:
      - pdns-admin-uwsgi

networks:
  pdns:
    external: true
    name: pdns
volumes:
  pdns-mysql:
    external: true```

**Comment by pschiffe** [comment]
`- PDNS_ADMIN_SQLA_DB_PORT=3306` -> `- PDNS_ADMIN_SQLA_DB_PORT='3306'`

I know, it's stupid, sorry. I'll try to fix this use case somehow.
