### ISSUE TITLE
uWSGI not working PORT format incorrect error

### ISSUE THREAD

**Issue by vipinjn24** [pschiffe/docker-pdns#48]
Hi,

I tried to run the admin but the backend is giving me error and front end is showing nginx temporary unavailable page.

uWSGI error:
```

Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 257, in locate_app
    return find_best_app(script_info, module)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/opt/powerdns-admin/powerdnsadmin/__init__.py", line 63, in create_app
    app.config.from_object('powerdnsadmin.default_config')
  File "/usr/local/lib/python3.8/site-packages/flask/config.py", line 174, in from_object
    obj = import_string(obj)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/utils.py", line 568, in import_string
    __import__(import_name)
  File "/opt/powerdns-admin/powerdnsadmin/default_config.py", line 12
    PORT = tcp://10.107.79.80:11153
              ^
SyntaxError: invalid syntax
```

**Comment by vipinjn24** [comment]
Below is the yaml used.

```
apiVersion: v1
kind: Service
metadata:
  name: pdns-admin
  namespace: dns
  labels:
    app: pdns-admin
    type: dns
  annotations:
    metallb.universe.tf/allow-shared-ip: internal-facing
    metallb.universe.tf/address-pool: private-ip
spec:
  type: LoadBalancer
  selector:
    app: pdns-admin
    type: dns
  ports:
  - name: pdns-admin
    protocol: TCP
    port: 11153
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pdns-admin
    type: dns
  name: pdns-admin
  namespace: dns
spec:
  selector:
    matchLabels:
      app: pdns-admin
      type: dns
  template:
    metadata:
      labels:
        app: pdns-admin
        type: dns
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "pdns-admin-uwsgi"
      containers:
      - name: pdns-admin-static
        image: pschiffe/pdns-admin-static:ngoduykhanh
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      - name: pdns-admin-uwsgi
        image: pschiffe/pdns-admin-uwsgi:ngoduykhanh
        imagePullPolicy: IfNotPresent
        env:
        - name: PDNS_ADMIN_SQLA_DB_HOST
          value: "'mysql.db'"
        - name: PDNS_ADMIN_SQLA_DB_PORT
          value: "'3306'"
        - name: PDNS_ADMIN_SQLA_DB_USER
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: quotedmysqluser
        - name: PDNS_ADMIN_SQLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: quotedmysqlpass
        - name: PDNS_ADMIN_SQLA_DB_NAME
          value: "'power_dns_admin_live'"
        - name: PDNS_API_URL
          value: "http://pdns-api:8081/"
        - name: PDNS_VERSION
          value: "4.2.1"
        - name: PDNS_API_KEY
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: apikey
        volumeMounts:
          - name: uploads
            mountPath: /opt/powerdns-admin/upload/
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: pdns-admin-pvc
```

**Comment by vipinjn24** [comment]
got it how to resolve this issue.
i was using pdn-api and pdns-admin and pdns-tcp and pdns-udp as the service names for this deployment.
due to this kubernetes was setting PDNS_ADMIN_PORT for pdns-admin service.
now changed the names to powerdns instead of pdns resolved the issue.
