### ISSUE TITLE
pdns-admin-uwsgi python error

### ISSUE THREAD

**Issue by nmahadkar** [pschiffe/docker-pdns#5]
Getting the following error while deploying `pdns-admin-uwsgi`
```
Traceback (most recent call last):
pdns-admin-uwsgi    |   File "/opt/powerdns-admin/create_db.py", line 6, in <module>
pdns-admin-uwsgi    |     from app import db
pdns-admin-uwsgi    |   File "/opt/powerdns-admin/app/__init__.py", line 52, in <module>
pdns-admin-uwsgi    |     from app import views, models
pdns-admin-uwsgi    |   File "/opt/powerdns-admin/app/views.py", line 17, in <module>
pdns-admin-uwsgi    |     from .models import User, Domain, Record, Server, History, Anonymous, Setting, Language, DomainSetting, Page
pdns-admin-uwsgi    |   File "/opt/powerdns-admin/app/models.py", line 44, in <module>
pdns-admin-uwsgi    |     API_EXTENDED_URL = utils.pdns_api_extended_uri(PDNS_VERSION)
pdns-admin-uwsgi    |   File "/opt/powerdns-admin/app/lib/utils.py", line 146, in pdns_api_extended_uri
pdns-admin-uwsgi    |     if StrictVersion(version) >= StrictVersion('4.0.0'):
pdns-admin-uwsgi    |   File "/usr/lib64/python2.7/distutils/version.py", line 140, in __cmp__
pdns-admin-uwsgi    |     compare = cmp(self.version, other.version)
pdns-admin-uwsgi    | AttributeError: StrictVersion instance has no attribute 'version'
```

What can I do to fix this?

**Comment by pschiffe** [comment]
Hello, I've just updated the images and I couldn't reproduce your problem. Can you please try it again with fresh images?

**Comment by pschiffe** [comment]
Feel free to reopen with more info.
