### ISSUE TITLE
Update to 4.6 breaks `envtpl` on startup

### ISSUE THREAD

**Issue by spijet** [pschiffe/docker-pdns#70]
Hello @pschiffe!

I just pulled the new images and found that my PowerDNS instance is unable to start. Here's the log I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/envtpl", line 33, in <module>
    sys.exit(load_entry_point('envtpl==0.6.0', 'console_scripts', 'envtpl')())
  File "/usr/local/bin/envtpl", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/envtpl.py", line 150, in <module>
    @jinja2.contextfunction
AttributeError: module 'jinja2' has no attribute 'contextfunction'
pdns_powerdns_1 exited with code 1
```

This happens on both Fedora-based and Alpine-based images, the only difference being the Python version (3.10 on Fedora and 3.9 on Alpine).

**Comment by acaranta** [comment]
Confirmed here too, containers are on a infinite error loop, had to rollback to 4.5 tag, the whole DNS infra went down 🙈 (Bad monitoring on my side lol)

**Comment by pschiffe** [comment]
Fck, sorry guys. Fixed images are already being built.

**Comment by spijet** [comment]
Maybe you should consider switching to some golang-based template renderer, like `gotpl`? That way there would be no need to pull in Python in `pdns` images. :)

**Comment by pschiffe** [comment]
Yeah, I'm considering it, since `envtpl` seems to be dead as well.

**Comment by pschiffe** [comment]
Follow up to this issue: #71

**Comment by acaranta** [comment]
Thx for correcting, but more than that... thanks for maintaining these images :)
